In [1]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.9.0-py3-none-any.whl.metadata (15 kB)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.18.5-py3-none-any.whl.metadata (7.2 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.11.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.13/site-packages (from optuna) (2.3.5)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.13/site-packages (from optuna) (25.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /opt/anaconda3/lib/python3.13/site-packages (from optuna) (2.0.43)
Requirement already satisfied: tqdm in /opt/anaconda3/lib/python3.13/site-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /opt/anaconda3/lib/python3.13/site-packages (from optuna) (6.0.3)
Collecting Mako (from alembic>=1.5.0->optuna)
  Downloading mako-1.3.12-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: typing-extensions>=4.12 in /opt/anaconda3/lib/python3.13/site-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /opt/anaconda3/lib/python3.13/site-packages (from Mako->alembic>=1.5.0->optuna) (3.0.2)
Downloading optuna-4.9.0-py3-none-any.whl (425 kB)
Downloading alembic-1.18.5-py3-none-any.whl (264 kB)
Downloading colorlog-6.11.0-py3-none-any.whl (12 kB)
Downloading mako-1.3.12-py3-none-any.whl (78 kB)
Installing collected packages: Mako, colorlog, alembic, optuna
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [optuna]━━━━ 3/4 [optuna]
Successfully installed Mako-1.3.12 alembic-1.18.5 colorlog-6.11.0 optuna-4.9.0

In [2]:
# Import necessary libraries
import optuna
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load the Pima Indian Diabetes dataset from sklearn
# Note: Scikit-learn's built-in 'load_diabetes' is a regression dataset.
# We will load the actual diabetes dataset from an external source
import pandas as pd

# Load the Pima Indian Diabetes dataset (from UCI repository)
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']

# Load the dataset
df = pd.read_csv(url, names=columns)

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [3]:
df.shape

(768, 9)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [9]:
df[df.duplicated()]

Empty DataFrame
Columns: [Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age, Outcome]
Index: []

In [10]:
import numpy as np

# Replace zero values with NaN in columns where zero is not a valid value
cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0, np.nan)

# Impute the missing values with the mean of the respective column
df.fillna(df.mean(), inplace=True)

# Check if there are any remaining missing values
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [11]:
# Split into features (X) and target (y)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Split data into training and test sets (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Optional: Scale the data for better model performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Check the shape of the data
print(f'Training set shape: {X_train.shape}')
print(f'Test set shape: {X_test.shape}')

Training set shape: (537, 8)
Test set shape: (231, 8)

In [12]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

#  The `suggest_*` Methods (Optuna)

| Method | Use for | Example |
|--------|---------|---------|
| `trial.suggest_int('name', low, high)` | Whole numbers | n_estimators, max_depth, batch_size |
| `trial.suggest_float('name', low, high)` | Decimals | learning rate, dropout rate |
| `trial.suggest_float('name', low, high, log=True)` | Decimals across orders of magnitude | learning rate ⭐ |
| `trial.suggest_categorical('name', [list])` | Choose from options | optimizer type, kernel, activation |

---

## Why do we use `log=True` for learning rate?

The **learning rate** can have values like:

```
0.0001
0.001
0.01
0.1
```

These values are **very far apart** (each is 10 times bigger than the previous one).

- **Without `log=True`:**
  - Optuna treats the range normally.
  - It picks **more values near larger numbers** (like 0.01–0.1).
  - Very small values (0.0001, 0.001) are rarely tested.
- **With `log=True`:**
  - Optuna gives **equal importance to every order of magnitude**.
  - It tries values like **0.0001, 0.001, 0.01, and 0.1** more fairly.
  - This increases the chance of finding the best learning rate.

In [13]:
# Create a study object and optimize the objective function
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2026-07-21 11:55:05,983] A new study created in memory with name: no-name-d0843168-4f59-411c-99ba-09f8a901521f
[I 2026-07-21 11:55:06,226] Trial 0 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 145, 'max_depth': 12}. Best is trial 0 with value: 0.7672253258845437.
[I 2026-07-21 11:55:06,335] Trial 1 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 80, 'max_depth': 8}. Best is trial 1 with value: 0.7709497206703911.
[I 2026-07-21 11:55:06,567] Trial 2 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 168, 'max_depth': 20}. Best is trial 1 with value: 0.7709497206703911.
[I 2026-07-21 11:55:06,718] Trial 3 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 108, 'max_depth': 10}. Best is trial 1 with value: 0.7709497206703911.
[I 2026-07-21 11:55:06,941] Trial 4 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 186, 'max_depth': 4}. Best is trial 1 with value: 0.7709497206703911.
[I 2026-07-21 11:55:07,103] Trial 5 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 115, 'max_depth': 16}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-07-21 11:55:07,325] Trial 6 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 161, 'max_depth': 10}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-07-21 11:55:07,438] Trial 7 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 89, 'max_depth': 5}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-07-21 11:55:07,630] Trial 8 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 138, 'max_depth': 14}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-07-21 11:55:07,903] Trial 9 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 196, 'max_depth': 20}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-07-21 11:55:07,987] Trial 10 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 57, 'max_depth': 16}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-07-21 11:55:08,063] Trial 11 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 51, 'max_depth': 16}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-07-21 11:55:08,136] Trial 12 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 17}. Best is trial 5 with value: 0.7783985102420856.
[I 2026-07-21 11:55:08,319] Trial 13 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 119, 'max_depth': 17}. Best is trial 13 with value: 0.7802607076350093.
[I 2026-07-21 11:55:08,489] Trial 14 finished with value: 0.7839851024208566 and parameters: {'n_estimators': 119, 'max_depth': 18}. Best is trial 14 with value: 0.7839851024208566.
[I 2026-07-21 11:55:08,658] Trial 15 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 118, 'max_depth': 18}. Best is trial 14 with value: 0.7839851024208566.
[I 2026-07-21 11:55:08,844] Trial 16 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 132, 'max_depth': 14}. Best is trial 14 with value: 0.7839851024208566.
[I 2026-07-21 11:55:08,993] Trial 17 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 103, 'max_depth': 19}. Best is trial 14 with value: 0.7839851024208566.
[I 2026-07-21 11:55:09,113] Trial 18 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 84, 'max_depth': 14}. Best is trial 14 with value: 0.7839851024208566.
[I 2026-07-21 11:55:09,328] Trial 19 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 153, 'max_depth': 18}. Best is trial 14 with value: 0.7839851024208566.
[I 2026-07-21 11:55:09,504] Trial 20 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 126, 'max_depth': 12}. Best is trial 14 with value: 0.7839851024208566.
[I 2026-07-21 11:55:09,662] Trial 21 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 110, 'max_depth': 16}. Best is trial 14 with value: 0.7839851024208566.
[I 2026-07-21 11:55:09,797] Trial 22 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 94, 'max_depth': 15}. Best is trial 14 with value: 0.7839851024208566.
[I 2026-07-21 11:55:09,968] Trial 23 finished with value: 0.7839851024208566 and parameters: {'n_estimators': 121, 'max_depth': 18}. Best is trial 14 with value: 0.7839851024208566.
[I 2026-07-21 11:55:10,071] Trial 24 finished with value: 0.7802607076350094 and parameters: {'n_estimators': 71, 'max_depth': 18}. Best is trial 14 with value: 0.7839851024208566.
[I 2026-07-21 11:55:10,178] Trial 25 finished with value: 0.7802607076350094 and parameters: {'n_estimators': 73, 'max_depth': 19}. Best is trial 14 with value: 0.7839851024208566.
[I 2026-07-21 11:55:10,277] Trial 26 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 68, 'max_depth': 18}. Best is trial 14 with value: 0.7839851024208566.
[I 2026-07-21 11:55:10,424] Trial 27 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 102, 'max_depth': 20}. Best is trial 14 with value: 0.7839851024208566.
[I 2026-07-21 11:55:10,522] Trial 28 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 67, 'max_depth': 18}. Best is trial 14 with value: 0.7839851024208566.
[I 2026-07-21 11:55:10,725] Trial 29 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 143, 'max_depth': 12}. Best is trial 14 with value: 0.7839851024208566.
[I 2026-07-21 11:55:10,973] Trial 30 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 174, 'max_depth': 13}. Best is trial 14 with value: 0.7839851024208566.
[I 2026-07-21 11:55:11,090] Trial 31 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 80, 'max_depth': 19}. Best is trial 14 with value: 0.7839851024208566.
[I 2026-07-21 11:55:11,196] Trial 32 finished with value: 0.7802607076350094 and parameters: {'n_estimators': 73, 'max_depth': 19}. Best is trial 14 with value: 0.7839851024208566.
[I 2026-07-21 11:55:11,330] Trial 33 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 94, 'max_depth': 20}. Best is trial 14 with value: 0.7839851024208566.
[I 2026-07-21 11:55:11,418] Trial 34 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 60, 'max_depth': 17}. Best is trial 14 with value: 0.7839851024208566.
[I 2026-07-21 11:55:11,529] Trial 35 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 76, 'max_depth': 19}. Best is trial 14 with value: 0.7839851024208566.
[I 2026-07-21 11:55:11,745] Trial 36 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 154, 'max_depth': 15}. Best is trial 14 with value: 0.7839851024208566.
[I 2026-07-21 11:55:11,928] Trial 37 finished with value: 0.7821229050279329 and parameters: {'n_estimators': 129, 'max_depth': 17}. Best is trial 14 with value: 0.7839851024208566.
[I 2026-07-21 11:55:12,109] Trial 38 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 127, 'max_depth': 17}. Best is trial 14 with value: 0.7839851024208566.
[I 2026-07-21 11:55:12,293] Trial 39 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 138, 'max_depth': 6}. Best is trial 14 with value: 0.7839851024208566.
[I 2026-07-21 11:55:12,544] Trial 40 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 175, 'max_depth': 15}. Best is trial 14 with value: 0.7839851024208566.
[I 2026-07-21 11:55:12,726] Trial 41 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 126, 'max_depth': 18}. Best is trial 14 with value: 0.7839851024208566.
[I 2026-07-21 11:55:12,887] Trial 42 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 112, 'max_depth': 20}. Best is trial 14 with value: 0.7839851024208566.
[I 2026-07-21 11:55:13,033] Trial 43 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 100, 'max_depth': 17}. Best is trial 14 with value: 0.7839851024208566.
[I 2026-07-21 11:55:13,161] Trial 44 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 88, 'max_depth': 19}. Best is trial 14 with value: 0.7839851024208566.
[I 2026-07-21 11:55:13,376] Trial 45 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 151, 'max_depth': 16}. Best is trial 14 with value: 0.7839851024208566.
[I 2026-07-21 11:55:13,536] Trial 46 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 134, 'max_depth': 3}. Best is trial 14 with value: 0.7839851024208566.
[I 2026-07-21 11:55:13,711] Trial 47 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 121, 'max_depth': 17}. Best is trial 14 with value: 0.7839851024208566.
[I 2026-07-21 11:55:13,933] Trial 48 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 143, 'max_depth': 18}. Best is trial 14 with value: 0.7839851024208566.
[I 2026-07-21 11:55:14,165] Trial 49 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 165, 'max_depth': 10}. Best is trial 14 with value: 0.7839851024208566.

In [14]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7839851024208566
Best hyperparameters: {'n_estimators': 119, 'max_depth': 18}

In [15]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

## Samplers in Optuna

In [16]:
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [17]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2026-07-21 12:04:42,089] A new study created in memory with name: no-name-393ca2b9-7452-471c-bcad-14968acce5d8
[I 2026-07-21 12:04:42,237] Trial 0 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 71, 'max_depth': 16}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:42,315] Trial 1 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 54, 'max_depth': 20}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:42,438] Trial 2 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 88, 'max_depth': 16}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:42,582] Trial 3 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 102, 'max_depth': 14}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:42,793] Trial 4 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 153, 'max_depth': 10}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:42,986] Trial 5 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 138, 'max_depth': 16}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:43,232] Trial 6 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 178, 'max_depth': 10}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:43,379] Trial 7 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 121, 'max_depth': 4}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:43,559] Trial 8 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 154, 'max_depth': 3}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:43,647] Trial 9 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 60, 'max_depth': 15}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:43,778] Trial 10 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 91, 'max_depth': 16}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:44,006] Trial 11 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 165, 'max_depth': 10}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:44,180] Trial 12 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 125, 'max_depth': 12}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:44,297] Trial 13 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 100, 'max_depth': 3}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:44,470] Trial 14 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 134, 'max_depth': 4}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:44,576] Trial 15 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 59, 'max_depth': 6}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:44,787] Trial 16 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 144, 'max_depth': 11}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:45,024] Trial 17 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 164, 'max_depth': 6}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:45,297] Trial 18 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 189, 'max_depth': 11}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:45,533] Trial 19 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 168, 'max_depth': 19}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:45,715] Trial 20 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 148, 'max_depth': 4}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:45,812] Trial 21 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 77, 'max_depth': 4}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:46,063] Trial 22 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 174, 'max_depth': 14}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:46,324] Trial 23 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 181, 'max_depth': 13}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:46,596] Trial 24 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 186, 'max_depth': 19}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:46,673] Trial 25 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 55, 'max_depth': 6}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:46,820] Trial 26 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 101, 'max_depth': 15}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:47,034] Trial 27 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 153, 'max_depth': 13}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:47,256] Trial 28 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 150, 'max_depth': 11}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:47,354] Trial 29 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 75, 'max_depth': 5}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:47,594] Trial 30 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 181, 'max_depth': 7}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:47,825] Trial 31 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 165, 'max_depth': 14}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:48,038] Trial 32 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 149, 'max_depth': 19}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:48,111] Trial 33 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 50, 'max_depth': 13}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:48,371] Trial 34 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 199, 'max_depth': 6}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:48,630] Trial 35 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 184, 'max_depth': 9}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:48,898] Trial 36 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 199, 'max_depth': 7}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:49,042] Trial 37 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 97, 'max_depth': 17}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:49,191] Trial 38 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 105, 'max_depth': 14}. Best is trial 0 with value: 0.7783985102420857.
[I 2026-07-21 12:04:49,267] Trial 39 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 54, 'max_depth': 7}. Best is trial 39 with value: 0.7802607076350093.
[I 2026-07-21 12:04:49,359] Trial 40 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 64, 'max_depth': 15}. Best is trial 39 with value: 0.7802607076350093.
[I 2026-07-21 12:04:49,631] Trial 41 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 194, 'max_depth': 16}. Best is trial 39 with value: 0.7802607076350093.
[I 2026-07-21 12:04:49,782] Trial 42 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 96, 'max_depth': 9}. Best is trial 39 with value: 0.7802607076350093.
[I 2026-07-21 12:04:49,983] Trial 43 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 153, 'max_depth': 6}. Best is trial 39 with value: 0.7802607076350093.
[I 2026-07-21 12:04:50,149] Trial 44 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 137, 'max_depth': 4}. Best is trial 39 with value: 0.7802607076350093.
[I 2026-07-21 12:04:50,369] Trial 45 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 169, 'max_depth': 6}. Best is trial 39 with value: 0.7802607076350093.
[I 2026-07-21 12:04:50,532] Trial 46 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 125, 'max_depth': 6}. Best is trial 39 with value: 0.7802607076350093.
[I 2026-07-21 12:04:50,745] Trial 47 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 152, 'max_depth': 18}. Best is trial 39 with value: 0.7802607076350093.
[I 2026-07-21 12:04:50,834] Trial 48 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 68, 'max_depth': 5}. Best is trial 39 with value: 0.7802607076350093.
[I 2026-07-21 12:04:51,099] Trial 49 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 190, 'max_depth': 10}. Best is trial 39 with value: 0.7802607076350093.

In [18]:
# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7802607076350093
Best hyperparameters: {'n_estimators': 54, 'max_depth': 7}

In [19]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

In [20]:
search_space = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [5, 10, 15, 20]
}

In [21]:
# Create a study and optimize it using GridSampler
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.GridSampler(search_space))
study.optimize(objective)

[I 2026-07-21 12:06:28,418] A new study created in memory with name: no-name-c88c24a7-c5a8-4bb0-87cf-08c7de10e62b
[I 2026-07-21 12:06:28,584] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-07-21 12:06:28,792] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-07-21 12:06:28,865] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-07-21 12:06:29,006] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-07-21 12:06:29,148] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-07-21 12:06:29,219] Trial 5 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-07-21 12:06:29,411] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-07-21 12:06:29,623] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-07-21 12:06:29,835] Trial 8 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 8 with value: 0.7746741154562384.
[I 2026-07-21 12:06:30,117] Trial 9 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 8 with value: 0.7746741154562384.
[I 2026-07-21 12:06:30,433] Trial 10 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 8 with value: 0.7746741154562384.
[I 2026-07-21 12:06:30,715] Trial 11 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 8 with value: 0.7746741154562384.
[I 2026-07-21 12:06:30,977] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 8 with value: 0.7746741154562384.
[I 2026-07-21 12:06:31,048] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 8 with value: 0.7746741154562384.
[I 2026-07-21 12:06:31,195] Trial 14 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 8 with value: 0.7746741154562384.
[I 2026-07-21 12:06:31,270] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 8 with value: 0.7746741154562384.

In [22]:
# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7746741154562384
Best hyperparameters: {'n_estimators': 150, 'max_depth': 15}

In [23]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74